version: "3"
services:
  registry:
    image: registry:2
    ports:
     - 5000:5000
    environment:
     - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/server_images
    restart: unless-stopped
    volumes:
     - ./server_images:/server_images
